### ISSUE TITLE
Cannot access all event attributes via sfRenderWindow_pollEvent

### ISSUE THREAD

**Issue by efrizoid** [JuliaMultimedia/CSFML.jl#2]
`sfRenderWindow_pollEvent` function works only with `sfEvent` type. How can I access event attributes other than event type (like mouse position or pressed key code) when using this function? These attributes are declared in other types like e.g. `sfMouseButtonEvent` and it looks to me that these are not accessible via `sfRenderWindow_pollEvent` function.
 
If I understand correctly, in CSFML `sfEvent` type should be union of more concrete event types like `sfKeyEvent`.

**Comment by Gnimuc** [comment]
Since [there is no one-to-one correspondence between Julia struct and C union](https://docs.julialang.org/en/latest/manual/calling-c-and-fortran-code/#Struct-Type-Correspondences-1), you need to use pointer arithmetic or some packages like Blobs.jl.

**Comment by Gnimuc** [comment]
`reinterpret` might also work.

**Comment by efrizoid** [comment]
Ok, thanks for the tips. I'm still wondering though... When julia creates `sfEvent` object it only allocates memory for the `type` attribute and C function gets only a pointer to that object. It then seems that C function could write to memory which does not belong to that `sfEvent` object when trying to manipulate other attributes which `sfEvent` union is assumed to have. Couldn't this lead to memory corruption or segfaults?

**Comment by Gnimuc** [comment]
Good question. I guess this might due to an old bug in Clang.jl, now it generates:
```
struct sfEvent
    key::sfKeyEvent
end
```
which is the largest field in the union. However, it is quite annoying for end-users when querying data from such a union. I'm going to overload `getproperty` to mimic the C union behavior, so users don't need to do pointer arithmetics.

**Comment by Gnimuc** [comment]
Hi @EimantasLedinauskas, it should work now, you could give the example in the master branch a try. BTW, would you like me to tag a new release for this change? 

My current plan is to wait [CEnum.jl's overhaul](https://github.com/JuliaInterop/CEnum.jl/pull/4) which will break everything that depends on it and then I'll regenerate the whole C bindings using Clang.jl. But if you're urgent, I'll tag the new release tomorrow.

**Comment by efrizoid** [comment]
Nice, thanks! It's not urgent, I can wait for the planned release :)
