### ISSUE TITLE
MethodError: no method matching sfEvent(::sfEventType)

### ISSUE THREAD

**Issue by JamesKCS** [JuliaMultimedia/CSFML.jl#5]
Hello,

The Quick start example does not work for me.  The problem line is:

`event_ref = Ref(sfEvent(sfEvtClosed))`

And the error is:

ERROR: LoadError: MethodError: no method matching sfEvent(::sfEventType)
Closest candidates are:
  sfEvent(::sfEventType, ::NTuple{20,UInt8}) at /home/james/.julia/packages/CSFML/KI9Y5/src/Window/window_common.jl:273
  sfEvent(::Any, ::Any) at /home/james/.julia/packages/CSFML/KI9Y5/src/Window/window_common.jl:273
Stacktrace:
 [1] top-level scope at /home/james/Julia_projs/tutorials/tutorial_main.jl:29
in expression starting at /home/james/Julia_projs/tutorials/tutorial_main.jl:29

I'm running Ubuntu 18.04.  Thank you in advance!

EDIT: The example in examples folder does work, I think the "Quick start" example in the README is just out of date.  I'd suggest either updating or removing the latter, so that others don't get confused in the future.

**Comment by Gnimuc** [comment]
Sorry, I forgot to update the README.
