### ISSUE TITLE
setting ContextSettings?

### ISSUE THREAD

**Issue by mlg556** [JuliaMultimedia/CSFML.jl#7]
I would like to set antialiasing in my window. I have tried:
```
mode = sfVideoMode(1280, 720, 32)
settings = sfContextSettings(0, 0, 3, 2, 2, 0, 0)
window = sfRenderWindow_create(mode, "SFML window", sfResize | sfClose, settings)
```
but this results in an error:
```
ERROR: MethodError: no method matching unsafe_convert(::Type{Ptr{sfContextSettings}}, ::sfContextSettings)
```

can anyone help?

**Comment by Gnimuc** [comment]
According to https://github.com/SFML/CSFML/blob/05847516fd94051641ccb525df0bed050b00fe4e/include/SFML/Graphics/RenderWindow.h#L55, we need to pass a pointer to the `sfContextSettings` to `sfRenderWindow_create`. In Julia, we use `settings_ref = Ref(sfContextSettings(0, 0, 3, 2, 2, 0, 0))`.

**Comment by mlg556** [comment]
that indeed works, thanks!
